# Generated by Django 4.0.4 on 2022-05-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='parentezco',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
