# Generated by Django 4.0.4 on 2022-05-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0002_familiar_parentezco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='parentezco',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
