# Generated by Django 4.0.4 on 2022-05-23 00:08

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0004_familiar_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='fecha_nacimiento',
            field=models.DateField(default=sqlalchemy.sql.expression.null),
        ),
    ]
