# Generated by Django 4.0.4 on 2022-05-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0007_alter_familiar_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='fecha_nacimiento',
        ),
    ]
